ARG DEBIAN_FRONTEND=noninteractive

FROM ghcr.io/osgeo/gdal:alpine-small-latest

ARG DEBIAN_FRONTEND

RUN apk add python3 py3-pip curl

RUN pip3 install --break-system-package flask

WORKDIR /app

COPY api.py /app/api.py

EXPOSE 5001
# Run Flask
#CMD ["python3", "api.py"]
CMD ["python3"]
#CMD ["flask", "run", "--host=0.0.0.0", "--port=5001"]
